---
- name: Deny trafic in
  ufw:
    default: deny
    direction: incoming

- name: Allow trafic out
  ufw:
    default: allow
    direction: outgoing

- name: Allow Ports
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - '80'
    - '22'
    - '9000'
    - '9001'
    - '3306'
    - '443'

- name: Enable UFW
  ufw:
    state: enabled
...    