---
- name: Update Nginx configuration
  template:
    src: ./roles/server/templates/nginx.conf.j2
    dest: /tmp/nginx/nginx.conf

#- name: copy index.html
#  template: 
#    src: ./roles/server/templates/index.html.j2 
#    dest: /tmp/nginx/index.html
#    mode: 0644

- name: Build Nginx image from Dockerfile
  community.docker.docker_image:
    name: my_nginx
    tag: my_img
    source: build
    build:
      path: /tmp/nginx
      

- name: Run nginx Container
  community.docker.docker_container:
    name: my_nginx
    image: my_nginx:my_img
    state: started
    ports:
      - "443:443"
    volumes:
      - web_data:/var/www/html
    networks:
      - name: inception_network